version: '3'
services:
  indexer-and-api:
    build: .
    volumes:
      - ./:/home/bun/app
    command: bun dev
    environment:
      - CHAIN_ID=31337
      - CHAIN_RPC_URL=host.docker.internal:8545/
      - START_FROM_BLOCK=
      - BLOCK_CONFIRMATIONS=0
      - BLOCK_FETCH_INTERVAL=5000
      - BLOCK_FETCH_BATCH_SIZE=10
      - CLEAR_DB=true
      - API_PORT=80
    ports:
      - '8080:80'
      - '8545:8545'
