version: '3'
services:
  indexer:
    build: .
    command: bun start:indexer
    environment:
      - CHAIN_ID=137
      - CHAIN_RPC_URL=https://polygon-rpc.com/
      - START_FROM_BLOCK=
      - BLOCK_CONFIRMATIONS=128
      - BLOCK_FETCH_INTERVAL=5000
      - BLOCK_FETCH_BATCH_SIZE=1000
      - DB_TYPE=postgres
      - DB_URL=
  api:
    build: .
    command: bun start:api
    environment:
      - CHAIN_ID=137
      - DB_TYPE=postgres
      - DB_URL=
      - API_PORT=80
    ports:
      - '80:80'
